version: '3.8'

services:
  php:
    build: .
    container_name: php-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
