# Use the Node.js base image
FROM node:18-alpine
# Set the working directory
WORKDIR /app
# Copy package.json and package-lock.json
COPY package*.json ./
# Install dependencies
RUN npm install
# Copy the rest of the application files
COPY . .
# Build the application
RUN npm run build
# Expose the port the app runs on
EXPOSE 3000
# Define the command to run the application
CMD ["npm", "run", "start:prod"]

# =================================================================
#   docker build -t nestjs-app .

# sudo  docker build -t nestjs-app .

# sudo  docker build -t nestjs-app -f dockerfile.prod . // production build

#  sudo docker run -p 3000:3000 nest_js

#   docker-compose up --build

# kubernetes
#   kebectl get namespaces
