version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel-app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        environment:
            - APP_ENV=local
            - APP_DEBUG=true
            - APP_KEY=base64:zccWRVmIe5pSJW6PNgWOaG2QQg4YffrVK28yYCaCn1Q=
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: laravel-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
